name: Model Heart

on: 
  push:
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          cd code
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          cd code
          python train.py  # Generate plot.png

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # cd assets
          echo "## CLASSIFICATION REPORT" >> report.md
          cat ../assets/metrics.txt >> report.md
          echo "## Visualization" >> report.md
          echo '![Feature Importance](../assets/feature_importance.png "Feature Importance")' >> report.md
          cml comment create report.md
